"""RugGuard MCP server.

Exposes two tools to MCP clients (Claude Desktop, Cursor, Heurist composers,
LangGraph runtimes, etc.):

  - `scan_token(chain, address)`  → 0-100 risk score + verdict + flags.
                                    `chain` accepts `base` or `solana`.
  - `explain_scan(scan_id)`       → audit-trail of a previously-cached scan.

Each tool call goes through the x402 paid round-trip transparently — the
server holds a dedicated EOA private key that signs the EIP-3009 USDC
transfer on Base. The agent never sees the payment friction.

Configuration (resolved in order, first hit wins):

  1. ~/.rugguard/wallet.json     — Generated by `python -m rugguard_mcp init`.
                                    Preferred: keeps the key off env vars
                                    (which leak into ps output, .bashrc
                                    history, child processes, etc.).
  2. RUGGUARD_X402_PRIVATE_KEY   — Env var fallback. Hex (with or without
                                    the 0x prefix).

  Other env vars:
    RUGGUARD_API_URL                 defaults to https://rugguard.redfleet.fr
    RUGGUARD_MCP_SESSION_SPEND_CAP_USD  default $5  — per-process cap
    RUGGUARD_MCP_DAILY_SPEND_CAP_USD    default $10 — rolling-24h cap

Spend safety (defense in depth — every layer alone is sufficient):
  - Use a dedicated wallet (generated by `init`), funded with only the USDC
    you're willing to spend. Treat the wallet balance itself as a hard cap.
  - The session cap stops a buggy agent that loops in one MCP session.
  - The 24 h cap stops a slow drain across multiple restarts.
  - When the wallet is empty, calls fail with `payment_rejected:...`. Top
    up the same address from any source — no need to restart the server.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP

from rugguard_mcp.x402_client import SpendCapExceededError, X402PaymentError, paid_get

DEFAULT_API_URL = "https://rugguard.redfleet.fr"
DEFAULT_WALLET_PATH = Path.home() / ".rugguard" / "wallet.json"

mcp = FastMCP("rugguard")


def _api_url() -> str:
    return os.environ.get("RUGGUARD_API_URL", DEFAULT_API_URL).rstrip("/")


def _wallet_path() -> Path:
    override = os.environ.get("RUGGUARD_MCP_WALLET_PATH")
    return Path(override).expanduser() if override else DEFAULT_WALLET_PATH


class WalletConfigError(RuntimeError):
    """Raised when the wallet config is present but unreadable/malformed.

    Distinct from "no wallet at all" because the response is different:
    no-wallet → tool returns missing_credentials so the agent surfaces
    onboarding. Corrupt-wallet → hard failure surfaced as wallet_config_
    error so the user notices BEFORE we silently fall back to a stale
    env var that might point at a different signing identity.
    """


def _private_key() -> str | None:
    """Resolve the EOA private key the MCP server uses to sign payments.

    Resolution order:
      1. `~/.rugguard/wallet.json` (preferred — kept off env vars).
      2. RUGGUARD_X402_PRIVATE_KEY env var (legacy fallback).

    Returns None when neither is present — the tool surfaces
    missing_credentials and the agent can guide the user through init.

    Security audit H3 (client track): if `wallet.json` EXISTS but cannot
    be parsed (corrupt JSON, permission denied, partial write from a
    crashed `init`), we used to silently fall through to the env var.
    That meant an attacker who could write/corrupt the wallet file but
    NOT delete it (read-only $HOME, denied unlink) — plus plant an env
    var via shell-rc injection — could swap the signing identity without
    the user noticing. Now we raise WalletConfigError loud: if the file
    is there, we trust ONLY what's in it. Missing file → env-var
    fallback as before.
    """
    path = _wallet_path()
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except OSError as exc:
            raise WalletConfigError(
                f"Wallet file at {path} exists but is unreadable ({type(exc).__name__}). "
                "Refusing to fall back to RUGGUARD_X402_PRIVATE_KEY — fix permissions or "
                "delete the file to regenerate."
            ) from exc
        except ValueError as exc:
            raise WalletConfigError(
                f"Wallet file at {path} exists but is not valid JSON "
                f"({type(exc).__name__}). Refusing to fall back — either repair the "
                "file or delete it and re-run `python -m rugguard_mcp init`."
            ) from exc
        pk = data.get("private_key") if isinstance(data, dict) else None
        if isinstance(pk, str) and pk:
            return pk
        raise WalletConfigError(
            f"Wallet file at {path} parsed but private_key field is missing or empty. "
            "Refusing to fall back — repair the file or delete and re-init."
        )
    return os.environ.get("RUGGUARD_X402_PRIVATE_KEY")


def _no_key_error() -> dict[str, Any]:
    return {
        "error": "missing_credentials",
        "message": (
            "RugGuard MCP server isn't configured to pay for scans. "
            "Run `python -m rugguard_mcp init` to generate a dedicated wallet, "
            "or set RUGGUARD_X402_PRIVATE_KEY for a Base mainnet EOA funded "
            "with USDC (≥ $0.05 recommended)."
        ),
    }


@mcp.tool()
async def scan_token(chain: str, address: str) -> dict[str, Any]:
    """Run a pre-trade rug-pull risk scan on a token contract.

    Returns a structured risk report. Pays $0.01 USDC on Base behind the
    scenes via x402. The spend is tracked against per-session and 24 h
    caps configured in the MCP server — if a cap is breached the call
    returns a `spend_cap_exceeded` error WITHOUT signing.

    Args:
        chain: Chain identifier. `base` for Base mainnet EVM token
            (14 heuristics). `solana` for Solana SPL mint (5 heuristics).
        address: Token contract address — `0x...` for EVM, base58 mint
            address for Solana.

    Returns:
        On success: {score: 0-100, verdict: safe|low_risk|medium_risk|high_risk|critical|uncertain,
                     score_confidence: high|medium|low|insufficient_data,
                     rug_probability_30d: 0.0-1.0,
                     flags: [{code, severity, evidence}, ...],
                     scan_id: uuid for follow-up via explain_scan(...)}.
        On failure: {error, message}. `error` is one of `missing_credentials`,
                    `spend_cap_exceeded`, `payment_failed`, `request_failed`,
                    `non_200`.
    """
    try:
        pk = _private_key()
    except WalletConfigError as exc:
        return {"error": "wallet_config_error", "message": str(exc)}
    if not pk:
        return _no_key_error()

    url = f"{_api_url()}/v1/scan/{chain}/{address}"
    try:
        status, body = await paid_get(url=url, private_key_hex=pk)
    except SpendCapExceededError as exc:
        return {
            "error": "spend_cap_exceeded",
            "cap_kind": exc.cap_kind,
            "cap_usd": exc.cap_usd,
            "would_be_total_usd": exc.would_be_total_usd,
            "message": str(exc),
        }
    except X402PaymentError as exc:
        return {"error": "payment_failed", "message": str(exc)}
    except Exception as exc:
        return {"error": "request_failed", "message": f"{type(exc).__name__}: {exc}"}

    if status != 200:
        return {"error": "non_200", "status": status, "body": body}
    return body


@mcp.tool()
async def explain_scan(scan_id: str) -> dict[str, Any]:
    """Fetch the per-heuristic audit trail of a previous scan.

    Costs $0.005 USDC. Use this when you need to know *why* a scan returned
    a specific verdict — e.g. for compliance, post-mortems, or building a
    user-visible explanation.

    Args:
        scan_id: UUID returned by a prior `scan_token` call.

    Returns:
        On success: {scan_id, scanned_at, score, verdict, heuristic_results: [...]}.
        On failure: {error, message}. Same error codes as `scan_token`.
    """
    try:
        pk = _private_key()
    except WalletConfigError as exc:
        return {"error": "wallet_config_error", "message": str(exc)}
    if not pk:
        return _no_key_error()

    url = f"{_api_url()}/v1/explain?scan_id={scan_id}"
    try:
        status, body = await paid_get(url=url, private_key_hex=pk)
    except SpendCapExceededError as exc:
        return {
            "error": "spend_cap_exceeded",
            "cap_kind": exc.cap_kind,
            "cap_usd": exc.cap_usd,
            "would_be_total_usd": exc.would_be_total_usd,
            "message": str(exc),
        }
    except X402PaymentError as exc:
        return {"error": "payment_failed", "message": str(exc)}
    except Exception as exc:
        return {"error": "request_failed", "message": f"{type(exc).__name__}: {exc}"}

    if status != 200:
        return {"error": "non_200", "status": status, "body": body}
    return body


def run() -> None:
    """Entrypoint used by `python -m rugguard_mcp` and the console script."""
    mcp.run()  # default transport: stdio


if __name__ == "__main__":
    run()
