"""RugGuard MCP server.

Exposes three tools to MCP clients (Claude Desktop, Cursor, Heurist composers,
LangGraph runtimes, etc.):

  - `scan_token(chain, address)`             → 0-100 risk score + verdict + flags.
                                               `chain` accepts `base` or `solana`.
  - `pretrade_check(chain, address,
        intended_trade_usd, policy)`         → prescriptive block | caution | allow
                                               recommendation + max_suggested_exposure_usd
                                               + signed JSON report (Ed25519). The
                                               firewall tool — call before each buy.
  - `explain_scan(scan_id)`                  → audit-trail of a previously-cached scan.

Each tool call goes through the x402 paid round-trip transparently — the
server holds a dedicated EOA private key that signs the EIP-3009 USDC
transfer on Base. The agent never sees the payment friction.

Configuration (resolved in order, first hit wins):

  1. ~/.rugguard/wallet.json     — Generated by `python -m rugguard_mcp init`.
                                    Preferred: keeps the key off env vars
                                    (which leak into ps output, .bashrc
                                    history, child processes, etc.).
  2. RUGGUARD_X402_PRIVATE_KEY   — Env var fallback. Hex (with or without
                                    the 0x prefix).

  Other env vars:
    RUGGUARD_API_URL                 defaults to https://rugguard.redfleet.fr
    RUGGUARD_MCP_SESSION_SPEND_CAP_USD  default $5  — per-process cap
    RUGGUARD_MCP_DAILY_SPEND_CAP_USD    default $10 — rolling-24h cap

Spend safety (defense in depth — every layer alone is sufficient):
  - Use a dedicated wallet (generated by `init`), funded with only the USDC
    you're willing to spend. Treat the wallet balance itself as a hard cap.
  - The session cap stops a buggy agent that loops in one MCP session.
  - The 24 h cap stops a slow drain across multiple restarts.
  - When the wallet is empty, calls fail with `payment_rejected:...`. Top
    up the same address from any source — no need to restart the server.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import httpx
from mcp.server.fastmcp import FastMCP

from rugguard_mcp.x402_client import (
    SpendCapExceededError,
    X402PaymentError,
    paid_get,
    paid_post,
)

METRICS_TIMEOUT_S = 10.0

DEFAULT_API_URL = "https://rugguard.redfleet.fr"
DEFAULT_WALLET_PATH = Path.home() / ".rugguard" / "wallet.json"


def _demo_mode() -> bool:
    """True when the operator has opted into demo mode (no wallet, no
    paid round-trip, canned scenarios). Set via:

      - env var `RUGGUARD_MCP_DEMO=1` (or any truthy value)
      - CLI flag `--demo` (sets the env var before server import)

    Read at call time, not import time, so tests can monkeypatch the env
    without juggling module reloads. Cheap (one env-var lookup).
    """
    return os.environ.get("RUGGUARD_MCP_DEMO", "").lower() in ("1", "true", "yes", "on")


# Demo scenarios. Mirror the shape of real responses byte-for-byte so a
# developer who builds against demo doesn't get surprises in production.
# The `_demo: true` field is added by the dispatcher so an agent can flag
# the response as non-authoritative — never make a real trade decision
# from these.
_DEMO_TIMESTAMP = "2026-05-17T00:00:00+00:00"
_DEMO_DISCLAIMER = "DEMO RESPONSE — not a real scan, do not trade on this."

_DEMO_SCAN_SAFE = {
    "scan_id": "demo-safe-01",
    "chain": "base",
    "contract": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "score": 12,
    "verdict": "safe",
    "score_confidence": "high",
    "rug_probability_30d": 0.02,
    "flags": [],
    "scanned_at": _DEMO_TIMESTAMP,
    "disclaimer": _DEMO_DISCLAIMER,
}
_DEMO_SCAN_CAUTION = {
    "scan_id": "demo-caution-01",
    "chain": "base",
    "contract": "0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed",
    "score": 62,
    "verdict": "medium_risk",
    "score_confidence": "high",
    "rug_probability_30d": 0.41,
    "flags": [
        {"code": "OWNER_NOT_RENOUNCED", "severity": "high",
         "evidence": "Owner has admin privileges and can call setTaxRate, blacklist, pause."},
        {"code": "TOP10_CONCENTRATION_HIGH", "severity": "high",
         "evidence": "Top 10 wallets hold 71% of supply (deployer + 9 fresh addresses)."},
    ],
    "scanned_at": _DEMO_TIMESTAMP,
    "disclaimer": _DEMO_DISCLAIMER,
}
_DEMO_SCAN_CRITICAL = {
    "scan_id": "demo-critical-01",
    "chain": "base",
    "contract": "0xfc0482b1abd9da4a90a512305eeac472ffb88e1f",
    "score": 95,
    "verdict": "critical",
    "score_confidence": "high",
    "rug_probability_30d": 0.88,
    "flags": [
        {"code": "TOP10_CONCENTRATION_HIGH", "severity": "critical",
         "evidence": "One wallet holds 94% of supply."},
        {"code": "LP_INSUFFICIENT_LIQUIDITY", "severity": "critical",
         "evidence": "LP holds 0.003 WETH, below the $50 floor."},
        {"code": "BYTECODE_SIMILAR_TO_RUG", "severity": "high",
         "evidence": "MinHash similarity 0.87 to a previously-rugged contract."},
    ],
    "scanned_at": _DEMO_TIMESTAMP,
    "disclaimer": _DEMO_DISCLAIMER,
}

_DEMO_SCAN_CYCLE = (_DEMO_SCAN_SAFE, _DEMO_SCAN_CAUTION, _DEMO_SCAN_CRITICAL)


def _demo_pick(address: str) -> dict[str, Any]:
    """Deterministic scenario picker: cycle safe/caution/critical based on
    the last hex char of the address. Same address always returns the same
    scenario across runs, so demos are reproducible."""
    last = address.strip().lower()[-1:] if address else "0"
    try:
        idx = int(last, 16) % 3
    except ValueError:
        idx = 0
    return dict(_DEMO_SCAN_CYCLE[idx])  # shallow copy so per-call _demo flag doesn't leak


def _demo_policy_decision(verdict: str, policy: str) -> tuple[str, float]:
    """Demo-mode mirror of the server's verdict -> policy_recommendation
    mapping. Returns (recommendation, exposure_multiplier).

      conservative: block at medium_risk or worse
      balanced   : block at high_risk or worse  (default)
      aggressive : block at critical only

    Exposure multiplier: 1.0 for allow, 0.2 for caution, 0.0 for block."""
    severity = {"safe": 0, "low_risk": 1, "medium_risk": 2, "high_risk": 3, "critical": 4}
    threshold = {"conservative": 2, "balanced": 3, "aggressive": 4}.get(policy, 3)
    s = severity.get(verdict, 4)
    if s >= threshold:
        return "block", 0.0
    if s >= threshold - 1:
        return "caution", 0.2
    return "allow", 1.0


def _demo_print_banner_once() -> None:
    """Print the demo banner to stderr once per process. Stderr because
    stdout is the MCP transport channel — anything we write there breaks
    the protocol. Use a module-level flag so we don't spam if multiple
    tool calls happen in the same session."""
    global _DEMO_BANNER_PRINTED
    if _DEMO_BANNER_PRINTED:
        return
    _DEMO_BANNER_PRINTED = True
    print(
        "==============================================================\n"
        "  RugGuard MCP — DEMO MODE\n"
        "  Returns canned scenarios. No wallet, no payment, no network\n"
        "  call to /v1/scan or /v1/pretrade/check. The `rugguard://metrics`\n"
        "  resource still serves real data — it is free.\n"
        "  Disable demo mode by unsetting RUGGUARD_MCP_DEMO and dropping\n"
        "  the --demo flag.\n"
        "==============================================================",
        file=sys.stderr,
    )


_DEMO_BANNER_PRINTED = False


mcp = FastMCP("rugguard")


def _api_url() -> str:
    return os.environ.get("RUGGUARD_API_URL", DEFAULT_API_URL).rstrip("/")


def _wallet_path() -> Path:
    override = os.environ.get("RUGGUARD_MCP_WALLET_PATH")
    return Path(override).expanduser() if override else DEFAULT_WALLET_PATH


class WalletConfigError(RuntimeError):
    """Raised when the wallet config is present but unreadable/malformed.

    Distinct from "no wallet at all" because the response is different:
    no-wallet → tool returns missing_credentials so the agent surfaces
    onboarding. Corrupt-wallet → hard failure surfaced as wallet_config_
    error so the user notices BEFORE we silently fall back to a stale
    env var that might point at a different signing identity.
    """


def _private_key() -> str | None:
    """Resolve the EOA private key the MCP server uses to sign payments.

    Resolution order:
      1. `~/.rugguard/wallet.json` (preferred — kept off env vars).
      2. RUGGUARD_X402_PRIVATE_KEY env var (legacy fallback).

    Returns None when neither is present — the tool surfaces
    missing_credentials and the agent can guide the user through init.

    Security audit H3 (client track): if `wallet.json` EXISTS but cannot
    be parsed (corrupt JSON, permission denied, partial write from a
    crashed `init`), we used to silently fall through to the env var.
    That meant an attacker who could write/corrupt the wallet file but
    NOT delete it (read-only $HOME, denied unlink) — plus plant an env
    var via shell-rc injection — could swap the signing identity without
    the user noticing. Now we raise WalletConfigError loud: if the file
    is there, we trust ONLY what's in it. Missing file → env-var
    fallback as before.
    """
    path = _wallet_path()
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except OSError as exc:
            raise WalletConfigError(
                f"Wallet file at {path} exists but is unreadable ({type(exc).__name__}). "
                "Refusing to fall back to RUGGUARD_X402_PRIVATE_KEY — fix permissions or "
                "delete the file to regenerate."
            ) from exc
        except ValueError as exc:
            raise WalletConfigError(
                f"Wallet file at {path} exists but is not valid JSON "
                f"({type(exc).__name__}). Refusing to fall back — either repair the "
                "file or delete it and re-run `python -m rugguard_mcp init`."
            ) from exc
        pk = data.get("private_key") if isinstance(data, dict) else None
        if isinstance(pk, str) and pk:
            return pk
        raise WalletConfigError(
            f"Wallet file at {path} parsed but private_key field is missing or empty. "
            "Refusing to fall back — repair the file or delete and re-init."
        )
    return os.environ.get("RUGGUARD_X402_PRIVATE_KEY")


def _no_key_error() -> dict[str, Any]:
    return {
        "error": "missing_credentials",
        "message": (
            "RugGuard MCP server isn't configured to pay for scans. "
            "Run `python -m rugguard_mcp init` to generate a dedicated wallet, "
            "or set RUGGUARD_X402_PRIVATE_KEY for a Base mainnet EOA funded "
            "with USDC (≥ $0.05 recommended)."
        ),
    }


@mcp.tool()
async def scan_token(chain: str, address: str) -> dict[str, Any]:
    """Run a pre-trade rug-pull risk scan on a token contract.

    Returns a structured risk report. Pays $0.01 USDC on Base behind the
    scenes via x402. The spend is tracked against per-session and 24 h
    caps configured in the MCP server — if a cap is breached the call
    returns a `spend_cap_exceeded` error WITHOUT signing.

    Args:
        chain: Chain identifier. `base` for Base mainnet EVM token
            (14 heuristics). `solana` for Solana SPL mint (5 heuristics).
        address: Token contract address — `0x...` for EVM, base58 mint
            address for Solana.

    Returns:
        On success: {score: 0-100, verdict: safe|low_risk|medium_risk|high_risk|critical|uncertain,
                     score_confidence: high|medium|low|insufficient_data,
                     rug_probability_30d: 0.0-1.0,
                     flags: [{code, severity, evidence}, ...],
                     scan_id: uuid for follow-up via explain_scan(...)}.
        On failure: {error, message}. `error` is one of `missing_credentials`,
                    `spend_cap_exceeded`, `payment_failed`, `request_failed`,
                    `non_200`.

        In demo mode (RUGGUARD_MCP_DEMO=1 or `--demo`): returns one of three
        canned scenarios deterministically by `address[-1]`. Response has
        `_demo: true` — never trade on this. No wallet, no network call.
    """
    if _demo_mode():
        _demo_print_banner_once()
        scenario = _demo_pick(address)
        scenario["chain"] = chain
        scenario["contract"] = address
        scenario["_demo"] = True
        return scenario

    try:
        pk = _private_key()
    except WalletConfigError as exc:
        return {"error": "wallet_config_error", "message": str(exc)}
    if not pk:
        return _no_key_error()

    url = f"{_api_url()}/v1/scan/{chain}/{address}"
    try:
        status, body = await paid_get(url=url, private_key_hex=pk)
    except SpendCapExceededError as exc:
        return {
            "error": "spend_cap_exceeded",
            "cap_kind": exc.cap_kind,
            "cap_usd": exc.cap_usd,
            "would_be_total_usd": exc.would_be_total_usd,
            "message": str(exc),
        }
    except X402PaymentError as exc:
        return {"error": "payment_failed", "message": str(exc)}
    except Exception as exc:
        return {"error": "request_failed", "message": f"{type(exc).__name__}: {exc}"}

    if status != 200:
        return {"error": "non_200", "status": status, "body": body}
    return body


@mcp.tool()
async def pretrade_check(
    chain: str,
    address: str,
    intended_trade_usd: float,
    policy: str = "balanced",
) -> dict[str, Any]:
    """Pre-trade firewall: returns a prescriptive `block | caution | allow`
    decision plus a clamped `max_suggested_exposure_usd`, given a token, a
    trade size, and the agent's risk policy.

    Costs $0.01 USDC on Base via x402 (same price as `scan_token`). Returns
    a signed JSON report when the deployment has signing configured — the
    `signature` and `key_fingerprint` fields prove what RugGuard said at the
    moment of trade, verifiable offline via the `rugguard-verify` CLI
    (`pip install rugguard-verify`) or against `GET /v1/pubkey`.

    Args:
        chain: `base` or `solana`.
        address: Token contract address (EVM 0x… or Solana base58).
        intended_trade_usd: Trade size in USD. Used to clamp the returned
            max_suggested_exposure_usd. Must be > 0 and ≤ $1B.
        policy: Agent risk tolerance. One of:
            - `conservative` — block at medium_risk or worse (score ≥ 51)
            - `balanced`     — block at high_risk or worse  (score ≥ 71)  [default]
            - `aggressive`   — block at critical only       (score ≥ 91)
            An `uncertain` verdict (sparse data) returns `caution` in all
            modes — absence of evidence is not evidence of safety.

    Returns:
        On success: {
            scan_id, chain, contract,
            policy_recommendation: block | caution | allow,
            policy, risk_score: 0-100, verdict, confidence,
            reason: [{code, severity}, ...],   # top 3 flags
            max_suggested_exposure_usd: float, # 100% if allow, 20% if caution, 0 if block
            intended_trade_usd, scanned_at, disclaimer,
            signature, key_fingerprint        # null when signing is unconfigured
        }
        On failure: {error, message}. Same error codes as `scan_token`.

    Disclaimer integrity: the `disclaimer` field is inside the signed bytes.
    Stripping or rewriting it breaks signature verification by design — a
    downstream proxy that drops the disclaimer will cause `rugguard-verify`
    to reject the report. That is the point.
    """
    # v0.2.3 client-side argument validation. The server enforces the
    # same constraints and returns 400 INVALID_*, but client-side
    # validation saves a round-trip charge_id reservation + the $0.01
    # paid round-trip for an obviously-invalid call.
    if chain not in ("base", "solana"):
        return {
            "error": "invalid_arguments",
            "message": (
                f"chain must be 'base' or 'solana' (got {chain!r}). "
                "RugGuard does not support other chains today."
            ),
        }
    if policy not in ("conservative", "balanced", "aggressive"):
        return {
            "error": "invalid_arguments",
            "message": (
                f"policy must be one of conservative/balanced/aggressive "
                f"(got {policy!r})."
            ),
        }
    if not (0 < intended_trade_usd <= 1_000_000_000):
        return {
            "error": "invalid_arguments",
            "message": (
                f"intended_trade_usd must be > 0 and ≤ $1B (got "
                f"{intended_trade_usd}). The $1B cap mirrors the server-side "
                "bound and stops a fat-fingered LLM from producing absurd "
                "max_suggested_exposure_usd values in the signed response."
            ),
        }

    if _demo_mode():
        _demo_print_banner_once()
        # Same address-based scenario picker as scan_token, but we also
        # map verdict -> policy_recommendation per the agent's policy.
        scan = _demo_pick(address)
        rec, exposure_mult = _demo_policy_decision(scan["verdict"], policy)
        return {
            "scan_id": scan["scan_id"].replace("demo-", "demo-pre-"),
            "chain": chain,
            "contract": address,
            "policy_recommendation": rec,
            "policy": policy,
            "risk_score": scan["score"],
            "verdict": scan["verdict"],
            "confidence": scan["score_confidence"],
            "reason": scan["flags"][:3],
            "max_suggested_exposure_usd": round(intended_trade_usd * exposure_mult, 2),
            "intended_trade_usd": intended_trade_usd,
            "scanned_at": _DEMO_TIMESTAMP,
            "disclaimer": _DEMO_DISCLAIMER,
            "signature": None,
            "key_fingerprint": None,
            "_demo": True,
        }

    try:
        pk = _private_key()
    except WalletConfigError as exc:
        return {"error": "wallet_config_error", "message": str(exc)}
    if not pk:
        return _no_key_error()

    url = f"{_api_url()}/v1/pretrade/check"
    payload = {
        "chain": chain,
        "contract": address,
        "intended_trade_usd": intended_trade_usd,
        "policy": policy,
    }
    try:
        status, body = await paid_post(url=url, json_body=payload, private_key_hex=pk)
    except SpendCapExceededError as exc:
        return {
            "error": "spend_cap_exceeded",
            "cap_kind": exc.cap_kind,
            "cap_usd": exc.cap_usd,
            "would_be_total_usd": exc.would_be_total_usd,
            "message": str(exc),
        }
    except X402PaymentError as exc:
        return {"error": "payment_failed", "message": str(exc)}
    except Exception as exc:
        return {"error": "request_failed", "message": f"{type(exc).__name__}: {exc}"}

    if status != 200:
        return {"error": "non_200", "status": status, "body": body}
    return body


@mcp.tool()
async def explain_scan(scan_id: str) -> dict[str, Any]:
    """Fetch the per-heuristic audit trail of a previous scan.

    Costs $0.005 USDC. Use this when you need to know *why* a scan returned
    a specific verdict — e.g. for compliance, post-mortems, or building a
    user-visible explanation.

    Args:
        scan_id: UUID returned by a prior `scan_token` call.

    Returns:
        On success: {scan_id, scanned_at, score, verdict, heuristic_results: [...]}.
        On failure: {error, message}. Same error codes as `scan_token`.

        In demo mode: returns a canned audit trail keyed by the scan_id
        suffix (`demo-safe-01`, `demo-caution-01`, `demo-critical-01`).
        Unknown scan_ids return a demo-safe trail. Response has `_demo: true`.
    """
    if _demo_mode():
        _demo_print_banner_once()
        # Match the scan_id back to its canned scenario. If the agent
        # passes an unrelated id (e.g. one from a real scan run earlier),
        # default to the safe scenario rather than 404 — the goal of demo
        # mode is "always something useful," not strict fidelity.
        if "critical" in scan_id:
            scenario = _DEMO_SCAN_CRITICAL
        elif "caution" in scan_id:
            scenario = _DEMO_SCAN_CAUTION
        else:
            scenario = _DEMO_SCAN_SAFE
        return {
            "scan_id": scan_id,
            "chain": scenario["chain"],
            "contract": scenario["contract"],
            "score": scenario["score"],
            "verdict": scenario["verdict"],
            "score_confidence": scenario["score_confidence"],
            "scanned_at": _DEMO_TIMESTAMP,
            "heuristic_results": [
                {"code": f.get("code"), "decision": "fail",
                 "severity": f.get("severity"), "evidence": f.get("evidence")}
                for f in scenario["flags"]
            ],
            "disclaimer": _DEMO_DISCLAIMER,
            "_demo": True,
        }

    try:
        pk = _private_key()
    except WalletConfigError as exc:
        return {"error": "wallet_config_error", "message": str(exc)}
    if not pk:
        return _no_key_error()

    url = f"{_api_url()}/v1/explain?scan_id={scan_id}"
    try:
        status, body = await paid_get(url=url, private_key_hex=pk)
    except SpendCapExceededError as exc:
        return {
            "error": "spend_cap_exceeded",
            "cap_kind": exc.cap_kind,
            "cap_usd": exc.cap_usd,
            "would_be_total_usd": exc.would_be_total_usd,
            "message": str(exc),
        }
    except X402PaymentError as exc:
        return {"error": "payment_failed", "message": str(exc)}
    except Exception as exc:
        return {"error": "request_failed", "message": f"{type(exc).__name__}: {exc}"}

    if status != 200:
        return {"error": "non_200", "status": status, "body": body}
    return body


# --- Free read-only resources (MCP `resources` primitive, not `tools`) ---
#
# Resources are read-only data the agent can inspect WITHOUT a payment.
# They show up in `list_resources()` and an agent can read them via
# `read_resource(uri)`. We expose RugGuard's live empirical recall +
# sample counts here so an agent (or human developer evaluating the
# service) can audit the methodology BEFORE deciding to pay for a scan.
#
# Differentiator on the doorstep: no competitor MCP rug-checker exists
# yet, and none of the API-only competitors (Rug Munch, SIBYL, CYBERA,
# Sentinel, DeFi Intelligence) publish their own miss rate. The MCP
# resource layer is where this becomes machine-discoverable.


@mcp.resource("rugguard://metrics", name="RugGuard live recall", mime_type="application/json")
async def metrics_resource() -> str:
    """Return RugGuard's live empirical recall + per-chain sample counts.

    Free (no x402 payment). Sources from `/v1/metrics` on the public API.
    The body is the same JSON shape as the HTTP endpoint, suitable for
    parsing by the agent or display in a chat for a human reviewer.

    Use this to:
      - Check the per-heuristic recall before pointing your funded wallet
        at the paid `scan_token` tool.
      - Audit what fraction of confirmed rugs each heuristic catches
        (the workhorse is `TOP10_CONCENTRATION_HIGH` at ~94 % on Base).
      - Read the methodology warning: HONEYPOT_* underperforms on the
        post-rug census (the contract is dead by the time we re-measure),
        but the forward sampler's T+30 follow-up gives the real
        product-time precision.
    """
    try:
        async with httpx.AsyncClient(timeout=METRICS_TIMEOUT_S) as client:
            r = await client.get(f"{_api_url()}/v1/metrics")
            r.raise_for_status()
            return r.text  # already JSON-stringified by the API
    except httpx.HTTPError as exc:
        # Surface a structured error AS JSON so the agent's parser doesn't
        # choke on a bare string. The agent can decide whether to retry.
        return json.dumps(
            {
                "error": "metrics_unreachable",
                "detail": f"{type(exc).__name__}: {str(exc)[:200]}",
                "hint": (
                    "RugGuard public API may be down or unreachable from this "
                    f"host. Try fetching {_api_url()}/v1/metrics directly."
                ),
            }
        )


def run() -> None:
    """Entrypoint used by `python -m rugguard_mcp` and the console script."""
    mcp.run()  # default transport: stdio


if __name__ == "__main__":
    run()
